#!/usr/bin/env node

const commands = require('./commands')

const userInputs = process.argv
const cmd = userInputs[2]
const id = userInputs[3]
const bookInfo = userInputs[4]
const editedBook = userInputs[4]

switch (cmd) {
  case 'listBooks':
    commands.listBooks()
    break
    case 'deleteBook':
    commands.deleteBook(id)
    break
    case 'addBook':
    commands.addBook(id, bookInfo)
    break
    case 'editBook':
    commands.editBook(id, editedBook)
    break

  default:
    console.log(`I don't understand: ${cmd}`)
}
